In [1]:
import numpy as np


In [5]:
arr=np.array([13,45,67,89])
print(arr.dtype)
print(type(arr))
print(arr.shape)

int64
<class 'numpy.ndarray'>
(4,)


In [6]:
arr1=np.zeros((3,4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
arr1=np.ones((3,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
arr4=np.arange(0,40,4)
print(arr4)

[ 0  4  8 12 16 20 24 28 32 36]


In [14]:
arr=np.array([1,2,4,23,5,6,4,6,90])
idx=[2,5,4,0]
print(arr[idx])

[4 6 5 1]
